### ISSUE TITLE
1.4.0 doesn't work.

### ISSUE THREAD

**Issue by RDKRACZ** [ExcessiveAmountsOfZombies/Croptopia#123]
**Fabric.**
After updating to 1.4.0 my game crashes instantly when starting

**Other Mods**
About ~100 other mods, I can upload a list but I think it's not incompat based on the log. 

```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config Croptopia.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'Croptopia.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1100)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 15 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 13 column 6 path $.mixins[4]
	at com.google.gson.Gson.fromJson(Gson.java:902)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1092)
	... 16 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 13 column 6 path $.mixins[4]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 18 more
Exiting with -1
Process exited with code 255
```

**Comment by RDKRACZ** [comment]
Seems like this is the same as #124 which was reported at the same time as this one.
