### ISSUE TITLE
Issue: cannot launch on server. damage durability error. no other mods installed.

### ISSUE THREAD

**Issue by Seiklus** [ExcessiveAmountsOfZombies/Croptopia#3]
[16:08:51] [main/INFO]: Reloading ResourceManager: Default, Croptopia, Fabric Tool Attribute API (v1)
[16:08:52] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.class_1867.method_8112()Ljava/lang/String;
        at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.server.Main.main(Main.java:139) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1867.method_8112()Ljava/lang/String;
        **at me.thonk.croptopia.recipe.DamageDurabilityRecipe.<init>(DamageDurabilityRecipe.java:14) ~[Croptopia-1.0.1-1.16.3-**FABRIC.jar:?]
        **at me.thonk.croptopia.recipe.DamageDurabilitySerializer.method_8142(DamageDurabilitySerializer.java:13) ~[Croptopia-1.0.1-1.16.3-FABRIC.jar:?]**
        at me.thonk.croptopia.recipe.DamageDurabilitySerializer.method_8121(DamageDurabilitySerializer.java:8) ~[Croptopia-1.0.1-1.16.3-FABRIC.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_231]

D:\MC Servers\FabricPack>pause
Press any key to continue . . .

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you for the report! This is fixed in c86e4a32266b88a08a975faeb26494099703ee3f
I've uploaded 1.0.2 to CurseForge and it is currently Under Review
