### ISSUE TITLE
Crash when trying to drink. Dehydration mod conflict.

### ISSUE THREAD

**Issue by RDKRACZ** [ExcessiveAmountsOfZombies/Croptopia#38]
[14:51:45] [Netty Local Client IO #0/INFO]: [CHAT] Gave [Rum§f] x1 to _K0RR_.
[14:51:49] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking player
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.1) ~[?:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:176) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:882) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91) ~[?:?]
	at net.minecraft.server.MinecraftServer.handler$cof000$modifiedRunLoop(MinecraftServer:7310) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchFieldError: HYDRATING_STEW
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.1) ~[?:?]
	at me.thonk.croptopia.dependencies.Dehydration.onUse(Dehydration.java:21) ~[Croptopia-1.16.3-4-FABRIC-1.1.0.jar:?]
	at me.thonk.croptopia.items.Drink.finishUsing(Drink.java:47) ~[Croptopia-1.16.3-4-FABRIC-1.1.0.jar:?]
	at net.minecraft.item.ItemStack.finishUsing(ItemStack:243) ~[?:?]
	at net.minecraft.entity.LivingEntity.redirect$dfc000$finishUsing(LivingEntity:18345) ~[?:?]
	at net.minecraft.entity.LivingEntity.consumeItem(LivingEntity:2941) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.redirect$ddb000$finishedUsingItem(ServerPlayerEntity:11157) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.consumeItem(ServerPlayerEntity:1140) ~[?:?]
	at net.minecraft.entity.LivingEntity.tickActiveItemStack(LivingEntity:2821) ~[?:?]
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2210) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity:274) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:434) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler:219) ~[?:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection:232) ~[?:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173) ~[?:?]
	... 7 more
[14:51:49] [Server thread/ERROR]: This crash report has been saved to:

**Comment by ExcessiveAmountsOfZombies** [comment]
which version of dehydration are you using? you need 1.0.8

**Comment by RDKRACZ** [comment]
Yes, I'm using Dehydration 1.0.8 and Croptopia 1.1.0.

**Comment by ExcessiveAmountsOfZombies** [comment]
ok, so the version on curseforge and the one I built with are apparently not the same. I'll have this fixed in the next version i release

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe this is fixed in 1.2.0 now.
