### ISSUE TITLE
Loot_Modifier_Serializers Failed to load in 1.19 update

### ISSUE THREAD

**Issue by TheaRTGGaming** [ExcessiveAmountsOfZombies/Croptopia#419]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19

### Croptopia version.

FORGE - 2.0.7

### What happened?

when loading minecraft Error code (Java.lang.nosuchfeldError: LOOT_MODIFER_SERIALIZERS) shows as the error code. that shows. should be a small easy fix.

### Relevant log.

-- MOD croptopia --
Details:
	Mod File: Croptopia-1.19-FORGE-2.0.7.jar
	Failure message: Croptopia (croptopia) has failed to load correctly
		java.lang.NoSuchFieldError: LOOT_MODIFIER_SERIALIZERS
	Mod Version: 2.0.7
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: LOOT_MODIFIER_SERIALIZERS
Stacktrace:
	at com.epherical.croptopia.CroptopiaForge.<clinit>(CroptopiaForge.java:82) ~[Croptopia-1.19-FORGE-2.0.7.jar%23158!/:2.0.7] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.98.jar%23190!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.98.jar%23189!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by krjencik** [comment]
same problem forge 41.0.98
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/9119754/latest.log)

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed since the 16th of july
