### ISSUE TITLE
Crash on startup with minecraft 1.19.2, mod version 2.2.0, recommended forge version

### ISSUE THREAD

**Issue by Oranamous** [ExcessiveAmountsOfZombies/Croptopia#489]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.2.0

### What happened?

Crash on startup, possible incompatibility with other mods I have. I press start in the launcher, and I can watch the output log for a few seconds before an error appears and the game crashes. Croptopia is mentioned in the log's error, and removing it solved the issue. I've included the log and mod list, if there's any workaround to this issue please let me know, thanks!

### Relevant logs

Version does not support log configuration, will assume one plaintext entry per line
2023-01-10 22:29:39,952 main WARN Advanced terminal features are not available in this environment
[22:29:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, [   ], --version, 1.19.2-forge-43.2.0, --gameDir, [   ], --assetsDir, C:\Users\[   ]\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, [   ], --accessToken, ????????, --clientId, [   ], --xuid, [   ], --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.0, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[22:29:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[22:29:41] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/[   ]/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[22:29:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\[   ]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.0\fmlcore-1.19.2-43.2.0.jar is missing mods.toml file
[22:29:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\[   ]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.0\javafmllanguage-1.19.2-43.2.0.jar is missing mods.toml file
[22:29:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\[   ]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.0\lowcodelanguage-1.19.2-43.2.0.jar is missing mods.toml file
[22:29:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\[   ]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.0\mclanguage-1.19.2-43.2.0.jar is missing mods.toml file
[22:29:41] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: flywheel. Using Mod File: [   ]\mods\flywheel-forge-1.19.2-0.6.8.jar
[22:29:41] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules kotlinforforge.obf and croptopia export package org.jetbrains.annotations to module apoli
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
Process crashed with exit code 1

### Additional information

(sorry for the big wall of text)

ars_creo-1.19.2-3.1.3
ars_nouveau-1.19.2-3.6.2
balm-4.5.3
BetterThirdPerson-Forge-1.19-1.9.0
caelus-forge-1.19.2-3.0.0.6
Clumps-forge-1.19.2-9.0.0+14
collection-of-singiro-1.19.x-1.1.3
create-1.19.2-0.5.0.g
Croptopia-1.19.2-FORGE-2.2.0
curios-forge-1.19.2-5.1.1.0
Essential-forge_1-19-2
ExplorersCompass-1.19.2-1.3.0-forge
FarmersDelight-1.19-1.2.0
flywheel-forge-1.19.2-0.6.8
GatewaysToEternity-1.19.2-3.1.1
geckolib-forge-1.19-3.1.39
genesis-1.19-1.0.2
Highlighter-1.19.1-1.1.4
Iceberg-1.19.2-forge-1.1.4
Jade-1.19.1-forge-8.7.0
jei-1.19.2-forge-11.5.0.297
MouseTweaks-fabric-mc1.19.3-2.24
naturalist-forge-2.1.1-1.19.2
NaturesCompass-1.19.2-1.10.0-forge
origins-forge-1.19.2-1.5.0.6-all
overweightfarming-1.19.2-2.0.0-fabric
Patchouli-1.19.2-77
Pehkui-3.6.3+1.19.2-forge
physics-mod-2.9.4-mc-1.19.x-forge
Placebo-1.19.2-7.1.1
soundphysics-forge-1.19.2-1.0.18
voicechat-forge-1.19.2-2.3.26
waystones-forge-1.19-11.1.0

**Comment by Oranamous** [comment]
After checking, it appears that this error doesn't happen in Croptopia 2.1.0, I'll use this version for now.

**Comment by DoctorSigma** [comment]
I confirm this problem for me.

**Comment by ExcessiveAmountsOfZombies** [comment]
2.2.1 should fix this, it removes the bundling of jetbrains annotations
