### ISSUE TITLE
Stacking Fertilized Dirt Blocks in world causes server crash

### ISSUE THREAD

**Issue by adkinss** [ExcessiveAmountsOfZombies/Croptopia#52]
**Version**
Croptopia 1.2.0

**Platform**
Fabric API 0.30.3+1.16

**Describe the issue**
I wanted to reach a beehive higher up in a tree and started placing dirt blocks, one on top of the other, to reach the hive.  I got a handful of blocks up and the server crashed.  Server is now in an endless crash loop.  I realized after the crash that I was using fertilized farmland as the dirt blocks and not regular dirt blocks.

**To Reproduce**
Place fertilized farmland in world, one on top of the other.  It doesn't take long to crash the server.

**Other Mods**
All of Fabric 3 v2.6.9

**Additional context**
Thread: Server thread
Stacktrace:
        at net.minecraft.class_1937.getChunkLithium(class_1937.java:5740)
        at net.minecraft.class_1937.method_8497(class_1937.java:5726)
        at net.minecraft.class_1937.method_8320(class_1937.java:408)
        at wraith.croptosis.block.FertilizedDirtBlock.method_9514(FertilizedDirtBlock.java:38)
        at wraith.croptosis.block.FertilizedDirtBlock.method_9514(FertilizedDirtBlock.java:52)
        at wraith.croptosis.block.FertilizedDirtBlock.method_9514(FertilizedDirtBlock.java:52)
        at wraith.croptosis.block.FertilizedDirtBlock.method_9514(FertilizedDirtBlock.java:52)
        at wraith.croptosis.block.FertilizedDirtBlock.method_9514(FertilizedDirtBlock.java:52)
        at wraith.croptosis.block.FertilizedDirtBlock.method_9514(FertilizedDirtBlock.java:52)
        ....

**Comment by adkinss** [comment]
And... wrong mod.  Wow.  The issue is with Croptosis, not Croptopia.  Sorry!
Closing this issue out.
