### ISSUE TITLE
[1.20.1] Dedicated server crash -Composter? Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 512 out of bounds for length 257

### ISSUE THREAD

**Issue by ProsperCraft** [ExcessiveAmountsOfZombies/Croptopia#545]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

forge-1.20.1-47.1.0

### Croptopia version.

Croptopia-1.20-FORGE-2.3.1

### What happened?

Server went down from Alex's mobs - https://github.com/AlexModGuy/AlexsMobs/issues/1702

Then didn't come back up because 
`Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 512 out of bounds for length 257
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1350) ~[fastutil-8.5.9.jar%2390!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.insert(Object2FloatOpenHashMap.java:249) ~[fastutil-8.5.9.jar%2390!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.put(Object2FloatOpenHashMap.java:257) ~[fastutil-8.5.9.jar%2390!/:?] {}
	at com.epherical.croptopia.Composter.registerCompostableItem`

### Relevant logs

Crash report - https://gist.github.com/ProsperCraft/d7ddd25b091575d574334d659c1bbf49

### Additional information

forge-1.20.1-47.1.0

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed the duplicate crops in 3.0
