### ISSUE TITLE
forge 48.1.0

### ISSUE THREAD

**Issue by Stormi2024** [ExcessiveAmountsOfZombies/Croptopia#589]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.2

### Croptopia version.

3.0.4

### What happened?

croptopia wont load correctly, i'm able to play as soon as i take it out.

### Relevant logs

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-01-15 09:12:47
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:48) ~[forge-1.20.2-48.1.0-universal.jar%23213!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:146) ~[forge-1.20.2-48.1.0-universal.jar%23213!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:584) ~[client-1.20.2-20230921.100330-srg.jar%23208!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:584) ~[client-1.20.2-20230921.100330-srg.jar%23208!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$6(Minecraft.java:575) ~[client-1.20.2-20230921.100330-srg.jar%23208!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.2-48.1.0-universal.jar%23213!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1382) ~[client-1.20.2-20230921.100330-srg.jar%23208!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1211) ~[client-1.20.2-20230921.100330-srg.jar%23208!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:781) ~[client-1.20.2-20230921.100330-srg.jar%23208!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.forge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] {}
	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD croptopia --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: com/epherical/epherolib/libs/org/spongepowered/configurate/loader/AbstractConfigurationLoader$Builder
		at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {}
		at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {}
		at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.2-48.1.0.jar%23210!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.2-48.1.0.jar%23209!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/lassk/AppData/Roaming/.minecraft/mods/Croptopia-1.20.2-FORGE-3.0.4.jar
	Failure message: Croptopia (croptopia) has failed to load correctly
		java.lang.NoClassDefFoundError: com/epherical/epherolib/libs/org/spongepowered/configurate/loader/AbstractConfigurationLoader$Builder
	Mod Version: 3.0.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: com.epherical.epherolib.libs.org.spongepowered.configurate.loader.AbstractConfigurationLoader$Builder
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:392) ~[securemodules-2.2.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:392) ~[securemodules-2.2.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {}
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.2-48.1.0.jar%23210!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.2-48.1.0.jar%23209!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1050412984 bytes (1001 MiB) / 1476395008 bytes (1408 MiB) up to 16106127360 bytes (15360 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4633
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 26038.45
	Virtual memory used (MB): 10786.44
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 31.71
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx15G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.20.2_HD_U_I7_pre1
	OptiFine Build: 20231221-121621
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.51+High.zip
	OpenGlVersion: 4.6.0 NVIDIA 546.33
	OpenGlRenderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
	ModLauncher: 10.1.1
	ModLauncher launch target: forge_client
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.2.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.1.1.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.1.1.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.1.1.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.1.1.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@48
		javafml@null
	Mod List: 
		client-1.20.2-20230921.100330-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		lucky-block-forge-1.20.2-13.0.jar                 |Lucky Block                   |lucky                         |1.20.2-13.0         |COMMON_SET|Manifest: NOSIGNATURE
		useful_backpacks-forge-1.20.2-2.0.1.123.jar       |Useful Backpacks              |usefulbackpacks               |2.0.1.123           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		MouseTweaks-forge-mc1.20.2-2.25.jar               |Mouse Tweaks                  |mousetweaks                   |2.25                |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.2.jar |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |COMMON_SET|Manifest: NOSIGNATURE
		harvestwithease-1.20.2-8.0.1.0-forge.jar          |Harvest with ease             |harvestwithease               |8.0.1.0             |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.20.2-4.3.1.jar                   |GeckoLib 4                    |geckolib                      |4.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		treeharvester-1.20.2-8.6.jar                      |Tree Harvester                |treeharvester                 |8.6                 |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.2-forge-16.0.0.28.jar                    |Just Enough Items             |jei                           |16.0.0.28           |COMMON_SET|Manifest: NOSIGNATURE
		spectrelib-forge-0.14.1+1.20.2.jar                |SpectreLib                    |spectrelib                    |0.14.1+1.20.2       |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-4.0.0+1.20.2.jar                     |Caelus API                    |caelus                        |4.0.0+1.20.2        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-6.1.0+1.20.2.jar                     |Curios API                    |curios                        |6.1.0+1.20.2        |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodcore-1.20-1.0.3.jar                     |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.20.2-FORGE-3.0.4.jar                  |Croptopia                     |croptopia                     |3.0.4               |ERROR     |Manifest: NOSIGNATURE
		collective-1.20.2-7.30.jar                        |Collective                    |collective                    |7.30                |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.20.2-5.9.18-forge.jar                |Journeymap                    |journeymap                    |5.9.18              |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.20.2-17.0.1.jar      |Cooking for Blockheads        |cookingforblockheads          |17.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-7.0.1+1.20.2.jar                   |Comforts                      |comforts                      |7.0.1+1.20.2        |COMMON_SET|Manifest: NOSIGNATURE
		tombstone-1.20.2-8.6.2.jar                        |Corail Tombstone              |tombstone                     |8.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		u_team_core-forge-1.20.2-5.2.0.270.jar            |U Team Core                   |uteamcore                     |5.2.0.270           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		endofherobrine-1.20.2-1.0.8.2.jar                 |The End of Herobrine          |endofherobrine                |1.0.8.2             |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.20.2-8.0.5.jar                       |Balm                          |balm                          |8.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		thedragonlib-1.20.2-1.0.0.jar                     |TheDragonLib                  |thedragonlib                  |1.20.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		charmofundying-forge-7.0.0+1.20.2.jar             |Charm of Undying              |charmofundying                |7.0.0+1.20.2        |COMMON_SET|Manifest: NOSIGNATURE
		extendedbonemeal-1.20.2-3.3.jar                   |Extended Bone Meal            |extendedbonemeal              |3.3                 |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.2-48.1.0-universal.jar                 |Forge                         |forge                         |48.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		stackrefill-1.20.2-4.2.jar                        |Stack Refill                  |stackrefill                   |4.2                 |COMMON_SET|Manifest: NOSIGNATURE
		cosmeticarmorreworked-1.20.2-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.2-v1a          |COMMON_SET|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		armorplus-1.20.2-20.0.0.jar                       |ArmorPlus                     |armorplus                     |1.20.2-20.0.0       |COMMON_SET|Manifest: NOSIGNATURE
		durabilitytooltip-1.1.5-forge-mc1.20.jar          |Durability Tooltip            |durabilitytooltip             |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: f416a141-d93e-4212-98e2-55210409faac
	FML: 48.1
	Forge: net.minecraftforge:48.1.0

### Additional information

armor plus, balm, caelus, charm of undying, collective, comforts. cooking for blockheads, cosmetic armor rework, croptopia, curios, durability tooltip, end of herobrine, extended bonemeal, gecko lib, grind enchantments, harvest with ease, jei, journey map, lucky block, mousetweaks, ham harvest craft 2 food core, preview optifine, stack refill, supermartijn642, thedragonlib, tombstone, treeharvester,u team core, useful backpacks

**Comment by ExcessiveAmountsOfZombies** [comment]
adding epherolib should fix this
